export const API_BASE_URL = import.meta.env.MODE === 'production' 
  ? '/api' 
  : 'http://localhost:8000';

export const SLIDER_CONFIG = {
  stress_level:            { min: 1,    max: 10,   step: 1,    label: 'Stress Level',            tooltip: 'Your overall perceived stress while gaming (1=calm, 10=overwhelming)',           section: 'mental' },
  anxiety_score:           { min: 0,    max: 10,   step: 0.1,  label: 'Anxiety Score',            tooltip: 'How anxious or nervous you feel during and after gaming sessions',              section: 'mental' },
  aggression_score:        { min: 0,    max: 10,   step: 0.1,  label: 'Aggression Score',         tooltip: 'How aggressively you tend to play or react to losses (0=calm, 10=very angry)',  section: 'mental' },
  loneliness_score:        { min: 0,    max: 10,   step: 0.1,  label: 'Loneliness Score',         tooltip: 'How lonely you feel in daily life (0=very social, 10=very isolated)',           section: 'social' },
  social_interaction_score:{ min: 0,    max: 10,   step: 0.1,  label: 'Social Interaction',       tooltip: 'Quality of real-world social interactions outside gaming (0=none, 10=high)',    section: 'social' },
  happiness_score:         { min: 0,    max: 10,   step: 0.1,  label: 'Happiness Score',          tooltip: 'General life happiness level (0=very unhappy, 10=very happy)',                  section: 'social' },
  depression_score:        { min: 0,    max: 10,   step: 0.1,  label: 'Depression Score',         tooltip: 'Level of depressive symptoms experienced (0=none, 10=severe)',                  section: 'mental' },
  daily_gaming_hours:      { min: 0,    max: 16,   step: 0.5,  label: 'Daily Gaming Hours',       tooltip: 'Average hours per day spent gaming',                                            section: 'session' },
  weekly_sessions:         { min: 1,    max: 50,   step: 1,    label: 'Weekly Sessions',          tooltip: 'Number of distinct gaming sessions per week',                                   section: 'session' },
  night_gaming_ratio:      { min: 0,    max: 1,    step: 0.05, label: 'Night Gaming Ratio',       tooltip: 'Proportion of gaming done after 10pm (0=never, 1=always)',                     section: 'session' },
  sleep_hours:             { min: 3,    max: 14,   step: 0.5,  label: 'Sleep Hours',              tooltip: 'Average hours of sleep per night',                                              section: 'session' },
  toxic_exposure:          { min: 0,    max: 1,    step: 0.05, label: 'Toxic Exposure',           tooltip: 'How often you encounter toxic/abusive players (0=never, 1=constantly)',        section: 'session' },
  microtransactions_spending: { min: 0, max: 500,  step: 5,    label: 'Monthly Spending ($)',     tooltip: 'Average monthly spending on in-game purchases and microtransactions',           section: 'session' },
  years_gaming:            { min: 0,    max: 30,   step: 1,    label: 'Years Gaming',             tooltip: 'How many years you have been gaming regularly',                                 section: 'session' },
};

export const SECTIONS = {
  session: { label: 'Session Behavior', icon: '🎮' },
  mental:  { label: 'Mental State',     icon: '🧠' },
  social:  { label: 'Social Factors',   icon: '👥' },
};

export const DEFAULT_VALUES = {
  stress_level: 5,
  anxiety_score: 5,
  aggression_score: 5,
  loneliness_score: 5,
  social_interaction_score: 5,
  happiness_score: 6,
  depression_score: 3,
  daily_gaming_hours: 3,
  weekly_sessions: 15,
  night_gaming_ratio: 0.3,
  sleep_hours: 7,
  toxic_exposure: 0.3,
  microtransactions_spending: 10,
  years_gaming: 3,
};

// Simulated player profiles with realistic behavioral traits
export const DUMMY_PLAYERS = [
  {
    "riotId": "TenZ#NA1",
    "rank": "Radiant",
    "agent": "Jett",
    "hours": 2100,
    "winRate": "61%",
    "presetValues": {
        "stress_level": 6,
        "anxiety_score": 4,
        "aggression_score": 5,
        "loneliness_score": 2,
        "social_interaction_score": 8,
        "happiness_score": 8,
        "depression_score": 1,
        "daily_gaming_hours": 8,
        "weekly_sessions": 35,
        "night_gaming_ratio": 0.4,
        "sleep_hours": 7,
        "toxic_exposure": 0.8,
        "microtransactions_spending": 150,
        "years_gaming": 10
    }
},
  {
    "riotId": "Shroud#EUW",
    "rank": "Radiant",
    "agent": "Omen",
    "hours": 4200,
    "winRate": "58%",
    "presetValues": {
        "stress_level": 4,
        "anxiety_score": 2,
        "aggression_score": 3,
        "loneliness_score": 3,
        "social_interaction_score": 7,
        "happiness_score": 8,
        "depression_score": 2,
        "daily_gaming_hours": 6,
        "weekly_sessions": 20,
        "night_gaming_ratio": 0.6,
        "sleep_hours": 8,
        "toxic_exposure": 0.4,
        "microtransactions_spending": 500,
        "years_gaming": 15
    }
},
  {
    "riotId": "VortexGhost#EUNE8509",
    "rank": "Silver",
    "agent": "Killjoy",
    "hours": 2176,
    "winRate": "53%",
    "presetValues": {
        "stress_level": 9,
        "anxiety_score": 5.7,
        "aggression_score": 0.8,
        "loneliness_score": 6.3,
        "social_interaction_score": 0.8,
        "happiness_score": 6.4,
        "depression_score": 9.9,
        "daily_gaming_hours": 13,
        "weekly_sessions": 7,
        "night_gaming_ratio": 0.75,
        "sleep_hours": 9,
        "toxic_exposure": 0.67,
        "microtransactions_spending": 380,
        "years_gaming": 27
    }
},
  {
    "riotId": "AlphaSpecter#SEA3380",
    "rank": "Platinum",
    "agent": "Skye",
    "hours": 1842,
    "winRate": "51%",
    "presetValues": {
        "stress_level": 7,
        "anxiety_score": 9,
        "aggression_score": 6.5,
        "loneliness_score": 0.1,
        "social_interaction_score": 1.4,
        "happiness_score": 1.8,
        "depression_score": 8.8,
        "daily_gaming_hours": 8.5,
        "weekly_sessions": 12,
        "night_gaming_ratio": 0.57,
        "sleep_hours": 8,
        "toxic_exposure": 0.23,
        "microtransactions_spending": 70,
        "years_gaming": 6
    }
},
  {
    "riotId": "ZeroWalker#JP5156",
    "rank": "Immortal",
    "agent": "Gekko",
    "hours": 2993,
    "winRate": "45%",
    "presetValues": {
        "stress_level": 1,
        "anxiety_score": 4,
        "aggression_score": 4.2,
        "loneliness_score": 0.7,
        "social_interaction_score": 1,
        "happiness_score": 6.5,
        "depression_score": 1.3,
        "daily_gaming_hours": 1.5,
        "weekly_sessions": 22,
        "night_gaming_ratio": 0.86,
        "sleep_hours": 8,
        "toxic_exposure": 0.17,
        "microtransactions_spending": 45,
        "years_gaming": 24
    }
},
  {
    "riotId": "SpaceSeeker#NA5279",
    "rank": "Ascendant",
    "agent": "Gekko",
    "hours": 3051,
    "winRate": "57%",
    "presetValues": {
        "stress_level": 7,
        "anxiety_score": 3.4,
        "aggression_score": 1.6,
        "loneliness_score": 6.4,
        "social_interaction_score": 9.5,
        "happiness_score": 7.7,
        "depression_score": 3.2,
        "daily_gaming_hours": 13.5,
        "weekly_sessions": 29,
        "night_gaming_ratio": 0.93,
        "sleep_hours": 8,
        "toxic_exposure": 0.2,
        "microtransactions_spending": 460,
        "years_gaming": 27
    }
},
  {
    "riotId": "BetaSniper#EUW759",
    "rank": "Immortal",
    "agent": "Killjoy",
    "hours": 1734,
    "winRate": "47%",
    "presetValues": {
        "stress_level": 1,
        "anxiety_score": 3.2,
        "aggression_score": 3.6,
        "loneliness_score": 8.1,
        "social_interaction_score": 8.6,
        "happiness_score": 9.7,
        "depression_score": 6.9,
        "daily_gaming_hours": 4,
        "weekly_sessions": 11,
        "night_gaming_ratio": 0.13,
        "sleep_hours": 4,
        "toxic_exposure": 0.65,
        "microtransactions_spending": 55,
        "years_gaming": 27
    }
},
  {
    "riotId": "StrikeBreaker#BR5125",
    "rank": "Iron",
    "agent": "KAY/O",
    "hours": 2224,
    "winRate": "57%",
    "presetValues": {
        "stress_level": 3,
        "anxiety_score": 3,
        "aggression_score": 2.4,
        "loneliness_score": 9.9,
        "social_interaction_score": 9.5,
        "happiness_score": 7,
        "depression_score": 2.4,
        "daily_gaming_hours": 14.5,
        "weekly_sessions": 19,
        "night_gaming_ratio": 0.06,
        "sleep_hours": 6.5,
        "toxic_exposure": 0.02,
        "microtransactions_spending": 210,
        "years_gaming": 0
    }
},
  {
    "riotId": "MegaRunner#SEA8694",
    "rank": "Gold",
    "agent": "Neon",
    "hours": 987,
    "winRate": "59%",
    "presetValues": {
        "stress_level": 10,
        "anxiety_score": 2.9,
        "aggression_score": 5.5,
        "loneliness_score": 6.7,
        "social_interaction_score": 3.5,
        "happiness_score": 6.3,
        "depression_score": 9.3,
        "daily_gaming_hours": 3,
        "weekly_sessions": 47,
        "night_gaming_ratio": 0.38,
        "sleep_hours": 7.5,
        "toxic_exposure": 0.53,
        "microtransactions_spending": 355,
        "years_gaming": 4
    }
},
  {
    "riotId": "ToxicDragon#OCE9373",
    "rank": "Radiant",
    "agent": "Gekko",
    "hours": 3916,
    "winRate": "58%",
    "presetValues": {
        "stress_level": 3,
        "anxiety_score": 7.7,
        "aggression_score": 0,
        "loneliness_score": 6.6,
        "social_interaction_score": 0.5,
        "happiness_score": 8.5,
        "depression_score": 3.9,
        "daily_gaming_hours": 11,
        "weekly_sessions": 20,
        "night_gaming_ratio": 0.43,
        "sleep_hours": 8.5,
        "toxic_exposure": 0.11,
        "microtransactions_spending": 130,
        "years_gaming": 13
    }
},
  {
    "riotId": "NightGhost#EUW1940",
    "rank": "Radiant",
    "agent": "Brimstone",
    "hours": 482,
    "winRate": "53%",
    "presetValues": {
        "stress_level": 3,
        "anxiety_score": 9.8,
        "aggression_score": 1.2,
        "loneliness_score": 0.7,
        "social_interaction_score": 9,
        "happiness_score": 1.1,
        "depression_score": 7.7,
        "daily_gaming_hours": 13,
        "weekly_sessions": 15,
        "night_gaming_ratio": 0.63,
        "sleep_hours": 8.5,
        "toxic_exposure": 0.56,
        "microtransactions_spending": 340,
        "years_gaming": 28
    }
},
  {
    "riotId": "WildKnight#VLR7542",
    "rank": "Ascendant",
    "agent": "Gekko",
    "hours": 1806,
    "winRate": "57%",
    "presetValues": {
        "stress_level": 4,
        "anxiety_score": 8.1,
        "aggression_score": 9.8,
        "loneliness_score": 6.1,
        "social_interaction_score": 3.8,
        "happiness_score": 0.1,
        "depression_score": 8.9,
        "daily_gaming_hours": 4,
        "weekly_sessions": 30,
        "night_gaming_ratio": 0.75,
        "sleep_hours": 10.5,
        "toxic_exposure": 0.56,
        "microtransactions_spending": 45,
        "years_gaming": 7
    }
},
  {
    "riotId": "SwiftAce#BR3330",
    "rank": "Immortal",
    "agent": "Chamber",
    "hours": 273,
    "winRate": "40%",
    "presetValues": {
        "stress_level": 5,
        "anxiety_score": 8.7,
        "aggression_score": 5.3,
        "loneliness_score": 0.9,
        "social_interaction_score": 1.6,
        "happiness_score": 6.7,
        "depression_score": 2.8,
        "daily_gaming_hours": 1,
        "weekly_sessions": 18,
        "night_gaming_ratio": 0.56,
        "sleep_hours": 13.5,
        "toxic_exposure": 0.43,
        "microtransactions_spending": 485,
        "years_gaming": 13
    }
},
  {
    "riotId": "BetaRogue#BR478",
    "rank": "Gold",
    "agent": "Killjoy",
    "hours": 372,
    "winRate": "62%",
    "presetValues": {
        "stress_level": 6,
        "anxiety_score": 7.4,
        "aggression_score": 6.1,
        "loneliness_score": 0,
        "social_interaction_score": 3.7,
        "happiness_score": 9.4,
        "depression_score": 6.7,
        "daily_gaming_hours": 14.5,
        "weekly_sessions": 21,
        "night_gaming_ratio": 0.73,
        "sleep_hours": 4.5,
        "toxic_exposure": 0.94,
        "microtransactions_spending": 475,
        "years_gaming": 3
    }
},
  {
    "riotId": "VortexNinja#BR4655",
    "rank": "Iron",
    "agent": "Raze",
    "hours": 2411,
    "winRate": "48%",
    "presetValues": {
        "stress_level": 3,
        "anxiety_score": 1.5,
        "aggression_score": 6,
        "loneliness_score": 0.3,
        "social_interaction_score": 9.8,
        "happiness_score": 1.1,
        "depression_score": 6.1,
        "daily_gaming_hours": 10,
        "weekly_sessions": 2,
        "night_gaming_ratio": 0.48,
        "sleep_hours": 5.5,
        "toxic_exposure": 0.37,
        "microtransactions_spending": 235,
        "years_gaming": 7
    }
},
  {
    "riotId": "SwiftBot#OCE3853",
    "rank": "Ascendant",
    "agent": "Jett",
    "hours": 2377,
    "winRate": "51%",
    "presetValues": {
        "stress_level": 1,
        "anxiety_score": 9.9,
        "aggression_score": 3.8,
        "loneliness_score": 3.1,
        "social_interaction_score": 3.1,
        "happiness_score": 1.1,
        "depression_score": 1.5,
        "daily_gaming_hours": 7.5,
        "weekly_sessions": 44,
        "night_gaming_ratio": 0.34,
        "sleep_hours": 10,
        "toxic_exposure": 0.48,
        "microtransactions_spending": 315,
        "years_gaming": 29
    }
},
  {
    "riotId": "GhostBlade#VLR7767",
    "rank": "Platinum",
    "agent": "Yoru",
    "hours": 2000,
    "winRate": "55%",
    "presetValues": {
        "stress_level": 10,
        "anxiety_score": 0.3,
        "aggression_score": 5.1,
        "loneliness_score": 5,
        "social_interaction_score": 7,
        "happiness_score": 8.6,
        "depression_score": 8,
        "daily_gaming_hours": 3.5,
        "weekly_sessions": 35,
        "night_gaming_ratio": 0.89,
        "sleep_hours": 4,
        "toxic_exposure": 0.11,
        "microtransactions_spending": 80,
        "years_gaming": 12
    }
},
  {
    "riotId": "LightWalker#LATAM6576",
    "rank": "Radiant",
    "agent": "Sage",
    "hours": 3202,
    "winRate": "43%",
    "presetValues": {
        "stress_level": 6,
        "anxiety_score": 2.8,
        "aggression_score": 1.9,
        "loneliness_score": 3.3,
        "social_interaction_score": 0.7,
        "happiness_score": 1.4,
        "depression_score": 2.9,
        "daily_gaming_hours": 12,
        "weekly_sessions": 29,
        "night_gaming_ratio": 0.28,
        "sleep_hours": 10,
        "toxic_exposure": 0,
        "microtransactions_spending": 280,
        "years_gaming": 27
    }
},
  {
    "riotId": "StormSpecter#EUW7806",
    "rank": "Radiant",
    "agent": "Harbor",
    "hours": 2560,
    "winRate": "61%",
    "presetValues": {
        "stress_level": 5,
        "anxiety_score": 4,
        "aggression_score": 8.3,
        "loneliness_score": 0.2,
        "social_interaction_score": 7,
        "happiness_score": 0.4,
        "depression_score": 6.4,
        "daily_gaming_hours": 12.5,
        "weekly_sessions": 42,
        "night_gaming_ratio": 0.18,
        "sleep_hours": 3,
        "toxic_exposure": 0.26,
        "microtransactions_spending": 235,
        "years_gaming": 8
    }
},
  {
    "riotId": "VortexGod#LATAM8058",
    "rank": "Iron",
    "agent": "Sova",
    "hours": 4800,
    "winRate": "42%",
    "presetValues": {
        "stress_level": 1,
        "anxiety_score": 9.9,
        "aggression_score": 9,
        "loneliness_score": 3.2,
        "social_interaction_score": 0.3,
        "happiness_score": 6.1,
        "depression_score": 2.4,
        "daily_gaming_hours": 12.5,
        "weekly_sessions": 20,
        "night_gaming_ratio": 0.08,
        "sleep_hours": 7.5,
        "toxic_exposure": 0.31,
        "microtransactions_spending": 160,
        "years_gaming": 8
    }
},
  {
    "riotId": "SilentGhost#OCE7346",
    "rank": "Silver",
    "agent": "Sova",
    "hours": 1361,
    "winRate": "55%",
    "presetValues": {
        "stress_level": 8,
        "anxiety_score": 2.9,
        "aggression_score": 9.1,
        "loneliness_score": 2,
        "social_interaction_score": 0.7,
        "happiness_score": 2.3,
        "depression_score": 3.5,
        "daily_gaming_hours": 12,
        "weekly_sessions": 1,
        "night_gaming_ratio": 0.34,
        "sleep_hours": 8,
        "toxic_exposure": 0.18,
        "microtransactions_spending": 135,
        "years_gaming": 30
    }
},
  {
    "riotId": "VortexRogue#KR3937",
    "rank": "Ascendant",
    "agent": "Deadlock",
    "hours": 389,
    "winRate": "41%",
    "presetValues": {
        "stress_level": 1,
        "anxiety_score": 4.3,
        "aggression_score": 1.3,
        "loneliness_score": 4,
        "social_interaction_score": 6.6,
        "happiness_score": 3.9,
        "depression_score": 7.1,
        "daily_gaming_hours": 9.5,
        "weekly_sessions": 4,
        "night_gaming_ratio": 0.07,
        "sleep_hours": 9,
        "toxic_exposure": 0.97,
        "microtransactions_spending": 405,
        "years_gaming": 29
    }
},
  {
    "riotId": "FrostRogue#BR4039",
    "rank": "Radiant",
    "agent": "Sage",
    "hours": 2699,
    "winRate": "61%",
    "presetValues": {
        "stress_level": 2,
        "anxiety_score": 3.1,
        "aggression_score": 0.3,
        "loneliness_score": 5.4,
        "social_interaction_score": 7.3,
        "happiness_score": 4.6,
        "depression_score": 8.6,
        "daily_gaming_hours": 2.5,
        "weekly_sessions": 35,
        "night_gaming_ratio": 0.79,
        "sleep_hours": 10,
        "toxic_exposure": 0.93,
        "microtransactions_spending": 145,
        "years_gaming": 8
    }
},
  {
    "riotId": "MegaReaper#BR429",
    "rank": "Bronze",
    "agent": "Iso",
    "hours": 4439,
    "winRate": "40%",
    "presetValues": {
        "stress_level": 7,
        "anxiety_score": 3.9,
        "aggression_score": 9.1,
        "loneliness_score": 3.8,
        "social_interaction_score": 5.3,
        "happiness_score": 9.4,
        "depression_score": 4.6,
        "daily_gaming_hours": 6,
        "weekly_sessions": 34,
        "night_gaming_ratio": 0.17,
        "sleep_hours": 9.5,
        "toxic_exposure": 0.38,
        "microtransactions_spending": 45,
        "years_gaming": 29
    }
},
  {
    "riotId": "BetaStalker#EUW9186",
    "rank": "Gold",
    "agent": "Skye",
    "hours": 3345,
    "winRate": "53%",
    "presetValues": {
        "stress_level": 6,
        "anxiety_score": 0.1,
        "aggression_score": 5.9,
        "loneliness_score": 0.3,
        "social_interaction_score": 7.6,
        "happiness_score": 5.6,
        "depression_score": 4.3,
        "daily_gaming_hours": 5,
        "weekly_sessions": 32,
        "night_gaming_ratio": 0.26,
        "sleep_hours": 13.5,
        "toxic_exposure": 0.91,
        "microtransactions_spending": 245,
        "years_gaming": 25
    }
},
  {
    "riotId": "FlameWraith#SEA5467",
    "rank": "Iron",
    "agent": "Breach",
    "hours": 2849,
    "winRate": "45%",
    "presetValues": {
        "stress_level": 8,
        "anxiety_score": 4.6,
        "aggression_score": 3.9,
        "loneliness_score": 6,
        "social_interaction_score": 3.6,
        "happiness_score": 8.4,
        "depression_score": 1.3,
        "daily_gaming_hours": 5.5,
        "weekly_sessions": 28,
        "night_gaming_ratio": 0.31,
        "sleep_hours": 9.5,
        "toxic_exposure": 0.55,
        "microtransactions_spending": 90,
        "years_gaming": 14
    }
},
  {
    "riotId": "FlameAce#EUNE612",
    "rank": "Gold",
    "agent": "Iso",
    "hours": 1834,
    "winRate": "52%",
    "presetValues": {
        "stress_level": 5,
        "anxiety_score": 7.3,
        "aggression_score": 4.2,
        "loneliness_score": 2.4,
        "social_interaction_score": 0.1,
        "happiness_score": 1.8,
        "depression_score": 8.6,
        "daily_gaming_hours": 0,
        "weekly_sessions": 36,
        "night_gaming_ratio": 0.81,
        "sleep_hours": 13,
        "toxic_exposure": 0.33,
        "microtransactions_spending": 200,
        "years_gaming": 30
    }
},
  {
    "riotId": "AlphaSniper#SEA1074",
    "rank": "Radiant",
    "agent": "Breach",
    "hours": 1982,
    "winRate": "62%",
    "presetValues": {
        "stress_level": 8,
        "anxiety_score": 6.4,
        "aggression_score": 5.4,
        "loneliness_score": 6.5,
        "social_interaction_score": 4.4,
        "happiness_score": 8.3,
        "depression_score": 0.5,
        "daily_gaming_hours": 15.5,
        "weekly_sessions": 16,
        "night_gaming_ratio": 0.55,
        "sleep_hours": 7.5,
        "toxic_exposure": 0.91,
        "microtransactions_spending": 255,
        "years_gaming": 10
    }
},
  {
    "riotId": "SolarBot#KR3240",
    "rank": "Diamond",
    "agent": "Chamber",
    "hours": 988,
    "winRate": "41%",
    "presetValues": {
        "stress_level": 9,
        "anxiety_score": 7.2,
        "aggression_score": 1.9,
        "loneliness_score": 7.4,
        "social_interaction_score": 8.9,
        "happiness_score": 9.1,
        "depression_score": 4.4,
        "daily_gaming_hours": 3,
        "weekly_sessions": 36,
        "night_gaming_ratio": 0.33,
        "sleep_hours": 10.5,
        "toxic_exposure": 0.59,
        "microtransactions_spending": 355,
        "years_gaming": 11
    }
},
  {
    "riotId": "ShadowWalker#JP5598",
    "rank": "Platinum",
    "agent": "Viper",
    "hours": 4232,
    "winRate": "60%",
    "presetValues": {
        "stress_level": 1,
        "anxiety_score": 4.7,
        "aggression_score": 4,
        "loneliness_score": 6.4,
        "social_interaction_score": 4,
        "happiness_score": 3.5,
        "depression_score": 6.6,
        "daily_gaming_hours": 14,
        "weekly_sessions": 28,
        "night_gaming_ratio": 0.5,
        "sleep_hours": 5.5,
        "toxic_exposure": 0.79,
        "microtransactions_spending": 80,
        "years_gaming": 30
    }
},
  {
    "riotId": "FlameSniper#SEA8655",
    "rank": "Immortal",
    "agent": "Viper",
    "hours": 3721,
    "winRate": "52%",
    "presetValues": {
        "stress_level": 1,
        "anxiety_score": 6,
        "aggression_score": 7.1,
        "loneliness_score": 6.4,
        "social_interaction_score": 1.3,
        "happiness_score": 6,
        "depression_score": 1.1,
        "daily_gaming_hours": 13.5,
        "weekly_sessions": 22,
        "night_gaming_ratio": 0.62,
        "sleep_hours": 8.5,
        "toxic_exposure": 0.81,
        "microtransactions_spending": 130,
        "years_gaming": 8
    }
},
  {
    "riotId": "FrostSniper#OCE9574",
    "rank": "Gold",
    "agent": "Viper",
    "hours": 1935,
    "winRate": "42%",
    "presetValues": {
        "stress_level": 10,
        "anxiety_score": 0.3,
        "aggression_score": 6.9,
        "loneliness_score": 0.9,
        "social_interaction_score": 3.8,
        "happiness_score": 0.9,
        "depression_score": 6.4,
        "daily_gaming_hours": 15,
        "weekly_sessions": 12,
        "night_gaming_ratio": 0.85,
        "sleep_hours": 6.5,
        "toxic_exposure": 0.1,
        "microtransactions_spending": 145,
        "years_gaming": 21
    }
},
  {
    "riotId": "DeadlyRogue#NA3391",
    "rank": "Diamond",
    "agent": "Neon",
    "hours": 2229,
    "winRate": "43%",
    "presetValues": {
        "stress_level": 7,
        "anxiety_score": 1.2,
        "aggression_score": 1.9,
        "loneliness_score": 9.7,
        "social_interaction_score": 9.8,
        "happiness_score": 0,
        "depression_score": 0.1,
        "daily_gaming_hours": 6.5,
        "weekly_sessions": 16,
        "night_gaming_ratio": 0.17,
        "sleep_hours": 6,
        "toxic_exposure": 0.26,
        "microtransactions_spending": 350,
        "years_gaming": 12
    }
},
  {
    "riotId": "EliteRogue#EUW3081",
    "rank": "Platinum",
    "agent": "Harbor",
    "hours": 268,
    "winRate": "54%",
    "presetValues": {
        "stress_level": 3,
        "anxiety_score": 0.1,
        "aggression_score": 9.1,
        "loneliness_score": 3.5,
        "social_interaction_score": 1,
        "happiness_score": 3.7,
        "depression_score": 0.6,
        "daily_gaming_hours": 9.5,
        "weekly_sessions": 41,
        "night_gaming_ratio": 0.68,
        "sleep_hours": 12.5,
        "toxic_exposure": 0.82,
        "microtransactions_spending": 40,
        "years_gaming": 1
    }
},
  {
    "riotId": "LightDragon#OCE1811",
    "rank": "Bronze",
    "agent": "Phoenix",
    "hours": 2112,
    "winRate": "63%",
    "presetValues": {
        "stress_level": 2,
        "anxiety_score": 2.2,
        "aggression_score": 8.3,
        "loneliness_score": 2.4,
        "social_interaction_score": 8.1,
        "happiness_score": 8.3,
        "depression_score": 7.6,
        "daily_gaming_hours": 2,
        "weekly_sessions": 14,
        "night_gaming_ratio": 0.55,
        "sleep_hours": 7,
        "toxic_exposure": 0.37,
        "microtransactions_spending": 305,
        "years_gaming": 16
    }
},
  {
    "riotId": "WildWalker#LATAM4378",
    "rank": "Ascendant",
    "agent": "Brimstone",
    "hours": 2217,
    "winRate": "54%",
    "presetValues": {
        "stress_level": 4,
        "anxiety_score": 6,
        "aggression_score": 5.5,
        "loneliness_score": 5.9,
        "social_interaction_score": 0.8,
        "happiness_score": 2,
        "depression_score": 9.9,
        "daily_gaming_hours": 0.5,
        "weekly_sessions": 9,
        "night_gaming_ratio": 0.58,
        "sleep_hours": 8,
        "toxic_exposure": 0.72,
        "microtransactions_spending": 425,
        "years_gaming": 12
    }
},
  {
    "riotId": "SadPhoenix#LATAM1117",
    "rank": "Silver",
    "agent": "Cypher",
    "hours": 3466,
    "winRate": "40%",
    "presetValues": {
        "stress_level": 10,
        "anxiety_score": 0.2,
        "aggression_score": 1.4,
        "loneliness_score": 3.8,
        "social_interaction_score": 3.8,
        "happiness_score": 0.2,
        "depression_score": 3.1,
        "daily_gaming_hours": 14.5,
        "weekly_sessions": 28,
        "night_gaming_ratio": 0.34,
        "sleep_hours": 10,
        "toxic_exposure": 0.26,
        "microtransactions_spending": 150,
        "years_gaming": 17
    }
},
  {
    "riotId": "ZeroBot#NA3861",
    "rank": "Diamond",
    "agent": "Viper",
    "hours": 996,
    "winRate": "43%",
    "presetValues": {
        "stress_level": 5,
        "anxiety_score": 3,
        "aggression_score": 0.4,
        "loneliness_score": 9.8,
        "social_interaction_score": 0.8,
        "happiness_score": 6.6,
        "depression_score": 0.3,
        "daily_gaming_hours": 1,
        "weekly_sessions": 17,
        "night_gaming_ratio": 0.08,
        "sleep_hours": 10,
        "toxic_exposure": 0.1,
        "microtransactions_spending": 455,
        "years_gaming": 12
    }
},
  {
    "riotId": "NeonRunner#KR3410",
    "rank": "Gold",
    "agent": "Reyna",
    "hours": 3149,
    "winRate": "62%",
    "presetValues": {
        "stress_level": 7,
        "anxiety_score": 9.9,
        "aggression_score": 1.8,
        "loneliness_score": 0.9,
        "social_interaction_score": 0.9,
        "happiness_score": 5.4,
        "depression_score": 5.4,
        "daily_gaming_hours": 0.5,
        "weekly_sessions": 44,
        "night_gaming_ratio": 0.52,
        "sleep_hours": 5.5,
        "toxic_exposure": 0.12,
        "microtransactions_spending": 50,
        "years_gaming": 26
    }
},
  {
    "riotId": "StrikeWalker#EUW2628",
    "rank": "Diamond",
    "agent": "Killjoy",
    "hours": 4316,
    "winRate": "46%",
    "presetValues": {
        "stress_level": 8,
        "anxiety_score": 6.6,
        "aggression_score": 2.4,
        "loneliness_score": 5.6,
        "social_interaction_score": 0.7,
        "happiness_score": 0.4,
        "depression_score": 0.9,
        "daily_gaming_hours": 0,
        "weekly_sessions": 3,
        "night_gaming_ratio": 0.54,
        "sleep_hours": 3.5,
        "toxic_exposure": 0.72,
        "microtransactions_spending": 235,
        "years_gaming": 12
    }
},
  {
    "riotId": "WildTiger#LATAM1499",
    "rank": "Ascendant",
    "agent": "Jett",
    "hours": 618,
    "winRate": "46%",
    "presetValues": {
        "stress_level": 8,
        "anxiety_score": 4,
        "aggression_score": 7.8,
        "loneliness_score": 4.9,
        "social_interaction_score": 2.8,
        "happiness_score": 4.6,
        "depression_score": 6.6,
        "daily_gaming_hours": 2.5,
        "weekly_sessions": 46,
        "night_gaming_ratio": 0.33,
        "sleep_hours": 10.5,
        "toxic_exposure": 0.53,
        "microtransactions_spending": 490,
        "years_gaming": 2
    }
},
  {
    "riotId": "ElitePlayer#OCE3343",
    "rank": "Platinum",
    "agent": "Deadlock",
    "hours": 3581,
    "winRate": "43%",
    "presetValues": {
        "stress_level": 7,
        "anxiety_score": 9.4,
        "aggression_score": 5.4,
        "loneliness_score": 5.5,
        "social_interaction_score": 3.5,
        "happiness_score": 4,
        "depression_score": 6.6,
        "daily_gaming_hours": 14,
        "weekly_sessions": 16,
        "night_gaming_ratio": 0.11,
        "sleep_hours": 4,
        "toxic_exposure": 0.28,
        "microtransactions_spending": 255,
        "years_gaming": 10
    }
},
  {
    "riotId": "NeonWarrior#EUNE6731",
    "rank": "Gold",
    "agent": "Phoenix",
    "hours": 2821,
    "winRate": "55%",
    "presetValues": {
        "stress_level": 8,
        "anxiety_score": 1.7,
        "aggression_score": 0.7,
        "loneliness_score": 9,
        "social_interaction_score": 1,
        "happiness_score": 8.7,
        "depression_score": 2.7,
        "daily_gaming_hours": 13.5,
        "weekly_sessions": 3,
        "night_gaming_ratio": 0.08,
        "sleep_hours": 12.5,
        "toxic_exposure": 0.98,
        "microtransactions_spending": 245,
        "years_gaming": 30
    }
},
  {
    "riotId": "AngryGhost#EUNE1193",
    "rank": "Gold",
    "agent": "Deadlock",
    "hours": 4803,
    "winRate": "50%",
    "presetValues": {
        "stress_level": 7,
        "anxiety_score": 5.6,
        "aggression_score": 0.8,
        "loneliness_score": 8,
        "social_interaction_score": 5.1,
        "happiness_score": 3.8,
        "depression_score": 4.7,
        "daily_gaming_hours": 0,
        "weekly_sessions": 38,
        "night_gaming_ratio": 0.45,
        "sleep_hours": 7,
        "toxic_exposure": 0.68,
        "microtransactions_spending": 140,
        "years_gaming": 27
    }
},
  {
    "riotId": "VortexKnight#EUW9016",
    "rank": "Ascendant",
    "agent": "Viper",
    "hours": 4997,
    "winRate": "59%",
    "presetValues": {
        "stress_level": 6,
        "anxiety_score": 6.4,
        "aggression_score": 9.2,
        "loneliness_score": 8.9,
        "social_interaction_score": 8,
        "happiness_score": 9.4,
        "depression_score": 4.6,
        "daily_gaming_hours": 2,
        "weekly_sessions": 19,
        "night_gaming_ratio": 0.81,
        "sleep_hours": 7,
        "toxic_exposure": 0.32,
        "microtransactions_spending": 490,
        "years_gaming": 30
    }
},
  {
    "riotId": "AlphaReaper#EUW768",
    "rank": "Ascendant",
    "agent": "Sage",
    "hours": 3620,
    "winRate": "56%",
    "presetValues": {
        "stress_level": 10,
        "anxiety_score": 0,
        "aggression_score": 1.1,
        "loneliness_score": 5.3,
        "social_interaction_score": 2.7,
        "happiness_score": 4.8,
        "depression_score": 9.8,
        "daily_gaming_hours": 3.5,
        "weekly_sessions": 16,
        "night_gaming_ratio": 0.81,
        "sleep_hours": 5.5,
        "toxic_exposure": 0.1,
        "microtransactions_spending": 245,
        "years_gaming": 27
    }
},
  {
    "riotId": "DeadlyKnight#BR8801",
    "rank": "Bronze",
    "agent": "KAY/O",
    "hours": 4230,
    "winRate": "64%",
    "presetValues": {
        "stress_level": 9,
        "anxiety_score": 4.2,
        "aggression_score": 1.7,
        "loneliness_score": 4.4,
        "social_interaction_score": 5.7,
        "happiness_score": 5.3,
        "depression_score": 8.6,
        "daily_gaming_hours": 7,
        "weekly_sessions": 31,
        "night_gaming_ratio": 0.96,
        "sleep_hours": 12.5,
        "toxic_exposure": 0.04,
        "microtransactions_spending": 420,
        "years_gaming": 8
    }
},
  {
    "riotId": "EliteSentinel#EUNE787",
    "rank": "Silver",
    "agent": "Yoru",
    "hours": 1395,
    "winRate": "57%",
    "presetValues": {
        "stress_level": 1,
        "anxiety_score": 3.9,
        "aggression_score": 4.3,
        "loneliness_score": 7.7,
        "social_interaction_score": 5.9,
        "happiness_score": 8.3,
        "depression_score": 8.5,
        "daily_gaming_hours": 7.5,
        "weekly_sessions": 23,
        "night_gaming_ratio": 0.16,
        "sleep_hours": 3.5,
        "toxic_exposure": 0.58,
        "microtransactions_spending": 205,
        "years_gaming": 28
    }
},
  {
    "riotId": "SadHunter#JP9537",
    "rank": "Ascendant",
    "agent": "Reyna",
    "hours": 2286,
    "winRate": "57%",
    "presetValues": {
        "stress_level": 2,
        "anxiety_score": 7.6,
        "aggression_score": 6.4,
        "loneliness_score": 5.8,
        "social_interaction_score": 7.4,
        "happiness_score": 2.1,
        "depression_score": 2.7,
        "daily_gaming_hours": 7.5,
        "weekly_sessions": 49,
        "night_gaming_ratio": 0.94,
        "sleep_hours": 12,
        "toxic_exposure": 0.44,
        "microtransactions_spending": 285,
        "years_gaming": 24
    }
},
  {
    "riotId": "SilentSeeker#LATAM218",
    "rank": "Silver",
    "agent": "Neon",
    "hours": 3175,
    "winRate": "53%",
    "presetValues": {
        "stress_level": 5,
        "anxiety_score": 5.4,
        "aggression_score": 6.4,
        "loneliness_score": 3.5,
        "social_interaction_score": 4.5,
        "happiness_score": 7.5,
        "depression_score": 2.7,
        "daily_gaming_hours": 10.5,
        "weekly_sessions": 46,
        "night_gaming_ratio": 0.8,
        "sleep_hours": 11,
        "toxic_exposure": 0.28,
        "microtransactions_spending": 285,
        "years_gaming": 8
    }
},
  {
    "riotId": "AlphaBreaker#LATAM3053",
    "rank": "Platinum",
    "agent": "Killjoy",
    "hours": 4956,
    "winRate": "64%",
    "presetValues": {
        "stress_level": 2,
        "anxiety_score": 3.5,
        "aggression_score": 6.4,
        "loneliness_score": 8.3,
        "social_interaction_score": 0,
        "happiness_score": 5.5,
        "depression_score": 7.3,
        "daily_gaming_hours": 15.5,
        "weekly_sessions": 27,
        "night_gaming_ratio": 0.28,
        "sleep_hours": 3.5,
        "toxic_exposure": 0.9,
        "microtransactions_spending": 310,
        "years_gaming": 20
    }
},
  {
    "riotId": "ZeroWolf#OCE5633",
    "rank": "Gold",
    "agent": "Omen",
    "hours": 1047,
    "winRate": "60%",
    "presetValues": {
        "stress_level": 7,
        "anxiety_score": 2.3,
        "aggression_score": 4.4,
        "loneliness_score": 1.5,
        "social_interaction_score": 7.9,
        "happiness_score": 3.7,
        "depression_score": 3.5,
        "daily_gaming_hours": 6.5,
        "weekly_sessions": 43,
        "night_gaming_ratio": 0.74,
        "sleep_hours": 7.5,
        "toxic_exposure": 0.77,
        "microtransactions_spending": 325,
        "years_gaming": 18
    }
},
  {
    "riotId": "NeonRogue#OCE4036",
    "rank": "Iron",
    "agent": "Fade",
    "hours": 4073,
    "winRate": "57%",
    "presetValues": {
        "stress_level": 10,
        "anxiety_score": 9.7,
        "aggression_score": 8.4,
        "loneliness_score": 5,
        "social_interaction_score": 1.1,
        "happiness_score": 4.1,
        "depression_score": 9.8,
        "daily_gaming_hours": 3,
        "weekly_sessions": 16,
        "night_gaming_ratio": 0.93,
        "sleep_hours": 10.5,
        "toxic_exposure": 0.22,
        "microtransactions_spending": 480,
        "years_gaming": 19
    }
},
  {
    "riotId": "FrostKing#VLR8434",
    "rank": "Iron",
    "agent": "Breach",
    "hours": 5046,
    "winRate": "61%",
    "presetValues": {
        "stress_level": 9,
        "anxiety_score": 5.2,
        "aggression_score": 4.3,
        "loneliness_score": 5.5,
        "social_interaction_score": 0.3,
        "happiness_score": 7.3,
        "depression_score": 5.7,
        "daily_gaming_hours": 6,
        "weekly_sessions": 8,
        "night_gaming_ratio": 0.21,
        "sleep_hours": 11,
        "toxic_exposure": 0.19,
        "microtransactions_spending": 220,
        "years_gaming": 24
    }
},
  {
    "riotId": "SaltySentinel#JP2865",
    "rank": "Immortal",
    "agent": "Fade",
    "hours": 2758,
    "winRate": "54%",
    "presetValues": {
        "stress_level": 3,
        "anxiety_score": 0.7,
        "aggression_score": 9.2,
        "loneliness_score": 5.8,
        "social_interaction_score": 6,
        "happiness_score": 6.7,
        "depression_score": 7.3,
        "daily_gaming_hours": 15.5,
        "weekly_sessions": 31,
        "night_gaming_ratio": 0.09,
        "sleep_hours": 9,
        "toxic_exposure": 0.4,
        "microtransactions_spending": 105,
        "years_gaming": 18
    }
},
  {
    "riotId": "DeadlyPhoenix#SEA2388",
    "rank": "Iron",
    "agent": "KAY/O",
    "hours": 2718,
    "winRate": "45%",
    "presetValues": {
        "stress_level": 2,
        "anxiety_score": 9.9,
        "aggression_score": 7,
        "loneliness_score": 8.6,
        "social_interaction_score": 0,
        "happiness_score": 3.8,
        "depression_score": 5.1,
        "daily_gaming_hours": 10.5,
        "weekly_sessions": 46,
        "night_gaming_ratio": 0.96,
        "sleep_hours": 4,
        "toxic_exposure": 0,
        "microtransactions_spending": 465,
        "years_gaming": 29
    }
},
  {
    "riotId": "SadRogue#JP3750",
    "rank": "Ascendant",
    "agent": "KAY/O",
    "hours": 4484,
    "winRate": "42%",
    "presetValues": {
        "stress_level": 5,
        "anxiety_score": 4.7,
        "aggression_score": 4.6,
        "loneliness_score": 4.5,
        "social_interaction_score": 7.1,
        "happiness_score": 6.8,
        "depression_score": 4.3,
        "daily_gaming_hours": 11,
        "weekly_sessions": 17,
        "night_gaming_ratio": 0.55,
        "sleep_hours": 13,
        "toxic_exposure": 0.64,
        "microtransactions_spending": 215,
        "years_gaming": 17
    }
},
  {
    "riotId": "WildBot#BR7292",
    "rank": "Silver",
    "agent": "Astra",
    "hours": 4073,
    "winRate": "40%",
    "presetValues": {
        "stress_level": 3,
        "anxiety_score": 9.2,
        "aggression_score": 8.5,
        "loneliness_score": 4.6,
        "social_interaction_score": 8.2,
        "happiness_score": 6.7,
        "depression_score": 5.5,
        "daily_gaming_hours": 5.5,
        "weekly_sessions": 38,
        "night_gaming_ratio": 0.26,
        "sleep_hours": 13,
        "toxic_exposure": 0.38,
        "microtransactions_spending": 210,
        "years_gaming": 22
    }
},
  {
    "riotId": "SpaceKing#BR8794",
    "rank": "Bronze",
    "agent": "Yoru",
    "hours": 1860,
    "winRate": "52%",
    "presetValues": {
        "stress_level": 6,
        "anxiety_score": 2.3,
        "aggression_score": 5.3,
        "loneliness_score": 1,
        "social_interaction_score": 4.2,
        "happiness_score": 6.6,
        "depression_score": 1.2,
        "daily_gaming_hours": 6,
        "weekly_sessions": 30,
        "night_gaming_ratio": 0.11,
        "sleep_hours": 6.5,
        "toxic_exposure": 0.88,
        "microtransactions_spending": 310,
        "years_gaming": 21
    }
},
  {
    "riotId": "GammaAce#LATAM313",
    "rank": "Radiant",
    "agent": "Harbor",
    "hours": 1004,
    "winRate": "47%",
    "presetValues": {
        "stress_level": 9,
        "anxiety_score": 8.1,
        "aggression_score": 9.8,
        "loneliness_score": 0,
        "social_interaction_score": 0.9,
        "happiness_score": 1.4,
        "depression_score": 5.6,
        "daily_gaming_hours": 15,
        "weekly_sessions": 9,
        "night_gaming_ratio": 0.77,
        "sleep_hours": 8.5,
        "toxic_exposure": 0.44,
        "microtransactions_spending": 245,
        "years_gaming": 22
    }
},
  {
    "riotId": "SpaceSniper#LATAM5351",
    "rank": "Immortal",
    "agent": "Neon",
    "hours": 3601,
    "winRate": "56%",
    "presetValues": {
        "stress_level": 5,
        "anxiety_score": 3.5,
        "aggression_score": 8.9,
        "loneliness_score": 8.7,
        "social_interaction_score": 5.5,
        "happiness_score": 5.6,
        "depression_score": 0.8,
        "daily_gaming_hours": 13,
        "weekly_sessions": 48,
        "night_gaming_ratio": 0.88,
        "sleep_hours": 5,
        "toxic_exposure": 0.06,
        "microtransactions_spending": 230,
        "years_gaming": 4
    }
},
  {
    "riotId": "FrostTiger#KR6310",
    "rank": "Platinum",
    "agent": "Yoru",
    "hours": 1173,
    "winRate": "58%",
    "presetValues": {
        "stress_level": 8,
        "anxiety_score": 0.9,
        "aggression_score": 9.9,
        "loneliness_score": 4.1,
        "social_interaction_score": 7.4,
        "happiness_score": 6.4,
        "depression_score": 9.2,
        "daily_gaming_hours": 0,
        "weekly_sessions": 28,
        "night_gaming_ratio": 0.73,
        "sleep_hours": 3.5,
        "toxic_exposure": 0.29,
        "microtransactions_spending": 225,
        "years_gaming": 15
    }
},
  {
    "riotId": "FlameStalker#BR7263",
    "rank": "Silver",
    "agent": "Yoru",
    "hours": 3414,
    "winRate": "50%",
    "presetValues": {
        "stress_level": 3,
        "anxiety_score": 1,
        "aggression_score": 7.2,
        "loneliness_score": 5,
        "social_interaction_score": 8,
        "happiness_score": 8.6,
        "depression_score": 5.1,
        "daily_gaming_hours": 8.5,
        "weekly_sessions": 14,
        "night_gaming_ratio": 0.16,
        "sleep_hours": 4.5,
        "toxic_exposure": 0.59,
        "microtransactions_spending": 195,
        "years_gaming": 18
    }
},
  {
    "riotId": "SadWraith#EUW2519",
    "rank": "Platinum",
    "agent": "Viper",
    "hours": 2687,
    "winRate": "52%",
    "presetValues": {
        "stress_level": 1,
        "anxiety_score": 2.5,
        "aggression_score": 5.4,
        "loneliness_score": 0.8,
        "social_interaction_score": 8.8,
        "happiness_score": 8.1,
        "depression_score": 2.3,
        "daily_gaming_hours": 0.5,
        "weekly_sessions": 45,
        "night_gaming_ratio": 0.96,
        "sleep_hours": 9,
        "toxic_exposure": 0.04,
        "microtransactions_spending": 305,
        "years_gaming": 16
    }
},
  {
    "riotId": "SilentRogue#LATAM5565",
    "rank": "Ascendant",
    "agent": "Brimstone",
    "hours": 3140,
    "winRate": "49%",
    "presetValues": {
        "stress_level": 3,
        "anxiety_score": 5.9,
        "aggression_score": 7.9,
        "loneliness_score": 7.6,
        "social_interaction_score": 8.6,
        "happiness_score": 9.3,
        "depression_score": 4.4,
        "daily_gaming_hours": 15.5,
        "weekly_sessions": 32,
        "night_gaming_ratio": 0.59,
        "sleep_hours": 9,
        "toxic_exposure": 0.83,
        "microtransactions_spending": 190,
        "years_gaming": 7
    }
},
  {
    "riotId": "ProBlade#JP2314",
    "rank": "Immortal",
    "agent": "Jett",
    "hours": 3788,
    "winRate": "42%",
    "presetValues": {
        "stress_level": 6,
        "anxiety_score": 5.8,
        "aggression_score": 9.8,
        "loneliness_score": 0.2,
        "social_interaction_score": 0.1,
        "happiness_score": 4.4,
        "depression_score": 0.4,
        "daily_gaming_hours": 9,
        "weekly_sessions": 38,
        "night_gaming_ratio": 0.22,
        "sleep_hours": 3,
        "toxic_exposure": 0.31,
        "microtransactions_spending": 325,
        "years_gaming": 21
    }
},
  {
    "riotId": "CasualAce#SEA8671",
    "rank": "Immortal",
    "agent": "Omen",
    "hours": 4389,
    "winRate": "45%",
    "presetValues": {
        "stress_level": 9,
        "anxiety_score": 6.9,
        "aggression_score": 9.2,
        "loneliness_score": 5.6,
        "social_interaction_score": 1.1,
        "happiness_score": 2.7,
        "depression_score": 5.4,
        "daily_gaming_hours": 3,
        "weekly_sessions": 44,
        "night_gaming_ratio": 0.36,
        "sleep_hours": 11.5,
        "toxic_exposure": 0.58,
        "microtransactions_spending": 330,
        "years_gaming": 16
    }
},
  {
    "riotId": "BetaGod#OCE2403",
    "rank": "Iron",
    "agent": "Deadlock",
    "hours": 2435,
    "winRate": "59%",
    "presetValues": {
        "stress_level": 3,
        "anxiety_score": 7.8,
        "aggression_score": 1.2,
        "loneliness_score": 1.7,
        "social_interaction_score": 2.3,
        "happiness_score": 6.6,
        "depression_score": 6,
        "daily_gaming_hours": 13.5,
        "weekly_sessions": 30,
        "night_gaming_ratio": 0.24,
        "sleep_hours": 10.5,
        "toxic_exposure": 0.63,
        "microtransactions_spending": 490,
        "years_gaming": 4
    }
},
  {
    "riotId": "LunarOracle#EUNE9046",
    "rank": "Iron",
    "agent": "Skye",
    "hours": 2625,
    "winRate": "48%",
    "presetValues": {
        "stress_level": 4,
        "anxiety_score": 8.5,
        "aggression_score": 3.3,
        "loneliness_score": 3.2,
        "social_interaction_score": 5.9,
        "happiness_score": 0.2,
        "depression_score": 9,
        "daily_gaming_hours": 13,
        "weekly_sessions": 10,
        "night_gaming_ratio": 0.38,
        "sleep_hours": 5,
        "toxic_exposure": 0.43,
        "microtransactions_spending": 140,
        "years_gaming": 23
    }
},
  {
    "riotId": "NightWalker#NA8769",
    "rank": "Bronze",
    "agent": "Killjoy",
    "hours": 2934,
    "winRate": "58%",
    "presetValues": {
        "stress_level": 3,
        "anxiety_score": 0.1,
        "aggression_score": 4.2,
        "loneliness_score": 8.7,
        "social_interaction_score": 7.3,
        "happiness_score": 8,
        "depression_score": 6.5,
        "daily_gaming_hours": 11,
        "weekly_sessions": 26,
        "night_gaming_ratio": 0.19,
        "sleep_hours": 10.5,
        "toxic_exposure": 0.15,
        "microtransactions_spending": 150,
        "years_gaming": 30
    }
},
  {
    "riotId": "BetaGhost#OCE2745",
    "rank": "Iron",
    "agent": "Reyna",
    "hours": 3554,
    "winRate": "41%",
    "presetValues": {
        "stress_level": 8,
        "anxiety_score": 1.7,
        "aggression_score": 6.8,
        "loneliness_score": 2.3,
        "social_interaction_score": 8.3,
        "happiness_score": 0.7,
        "depression_score": 7.7,
        "daily_gaming_hours": 9,
        "weekly_sessions": 23,
        "night_gaming_ratio": 0.12,
        "sleep_hours": 12,
        "toxic_exposure": 0.85,
        "microtransactions_spending": 280,
        "years_gaming": 1
    }
},
  {
    "riotId": "StrikeTiger#VLR108",
    "rank": "Immortal",
    "agent": "Harbor",
    "hours": 3110,
    "winRate": "53%",
    "presetValues": {
        "stress_level": 7,
        "anxiety_score": 4.7,
        "aggression_score": 3.7,
        "loneliness_score": 4.2,
        "social_interaction_score": 4.4,
        "happiness_score": 4.6,
        "depression_score": 0.8,
        "daily_gaming_hours": 7,
        "weekly_sessions": 7,
        "night_gaming_ratio": 0.14,
        "sleep_hours": 11,
        "toxic_exposure": 0.01,
        "microtransactions_spending": 480,
        "years_gaming": 16
    }
},
  {
    "riotId": "EliteGhost#OCE5712",
    "rank": "Platinum",
    "agent": "Cypher",
    "hours": 1687,
    "winRate": "40%",
    "presetValues": {
        "stress_level": 3,
        "anxiety_score": 7.9,
        "aggression_score": 9.6,
        "loneliness_score": 2.4,
        "social_interaction_score": 2,
        "happiness_score": 9.1,
        "depression_score": 1.6,
        "daily_gaming_hours": 13,
        "weekly_sessions": 47,
        "night_gaming_ratio": 0.89,
        "sleep_hours": 8.5,
        "toxic_exposure": 0.19,
        "microtransactions_spending": 400,
        "years_gaming": 30
    }
},
  {
    "riotId": "SolarMage#BR6565",
    "rank": "Ascendant",
    "agent": "Cypher",
    "hours": 4408,
    "winRate": "62%",
    "presetValues": {
        "stress_level": 10,
        "anxiety_score": 3.7,
        "aggression_score": 8.9,
        "loneliness_score": 6.3,
        "social_interaction_score": 7.1,
        "happiness_score": 0,
        "depression_score": 2.6,
        "daily_gaming_hours": 8,
        "weekly_sessions": 25,
        "night_gaming_ratio": 0.02,
        "sleep_hours": 7,
        "toxic_exposure": 0.58,
        "microtransactions_spending": 75,
        "years_gaming": 29
    }
},
  {
    "riotId": "EliteBreaker#VLR6530",
    "rank": "Radiant",
    "agent": "Raze",
    "hours": 4501,
    "winRate": "40%",
    "presetValues": {
        "stress_level": 3,
        "anxiety_score": 3.7,
        "aggression_score": 8.7,
        "loneliness_score": 6.5,
        "social_interaction_score": 6.6,
        "happiness_score": 9.4,
        "depression_score": 4.5,
        "daily_gaming_hours": 13.5,
        "weekly_sessions": 50,
        "night_gaming_ratio": 0.89,
        "sleep_hours": 6.5,
        "toxic_exposure": 0.76,
        "microtransactions_spending": 105,
        "years_gaming": 29
    }
},
  {
    "riotId": "SilentBot#KR6495",
    "rank": "Silver",
    "agent": "Brimstone",
    "hours": 2276,
    "winRate": "46%",
    "presetValues": {
        "stress_level": 2,
        "anxiety_score": 7.2,
        "aggression_score": 7.9,
        "loneliness_score": 4.7,
        "social_interaction_score": 4.2,
        "happiness_score": 5.7,
        "depression_score": 2.2,
        "daily_gaming_hours": 2,
        "weekly_sessions": 20,
        "night_gaming_ratio": 0.62,
        "sleep_hours": 13.5,
        "toxic_exposure": 0.13,
        "microtransactions_spending": 150,
        "years_gaming": 18
    }
},
  {
    "riotId": "ToxicTiger#EUNE4562",
    "rank": "Radiant",
    "agent": "Brimstone",
    "hours": 5030,
    "winRate": "40%",
    "presetValues": {
        "stress_level": 2,
        "anxiety_score": 1.9,
        "aggression_score": 4.9,
        "loneliness_score": 0.8,
        "social_interaction_score": 3.6,
        "happiness_score": 1.1,
        "depression_score": 5.2,
        "daily_gaming_hours": 9.5,
        "weekly_sessions": 12,
        "night_gaming_ratio": 0.38,
        "sleep_hours": 10.5,
        "toxic_exposure": 0.54,
        "microtransactions_spending": 255,
        "years_gaming": 5
    }
},
  {
    "riotId": "FrostRogue#OCE9505",
    "rank": "Silver",
    "agent": "Yoru",
    "hours": 93,
    "winRate": "41%",
    "presetValues": {
        "stress_level": 7,
        "anxiety_score": 3.8,
        "aggression_score": 2.2,
        "loneliness_score": 2.3,
        "social_interaction_score": 7,
        "happiness_score": 9.2,
        "depression_score": 0.6,
        "daily_gaming_hours": 3,
        "weekly_sessions": 39,
        "night_gaming_ratio": 0.01,
        "sleep_hours": 4.5,
        "toxic_exposure": 0.07,
        "microtransactions_spending": 395,
        "years_gaming": 23
    }
},
  {
    "riotId": "AngryRogue#EUW2499",
    "rank": "Bronze",
    "agent": "Neon",
    "hours": 799,
    "winRate": "56%",
    "presetValues": {
        "stress_level": 10,
        "anxiety_score": 1.6,
        "aggression_score": 1.7,
        "loneliness_score": 0.2,
        "social_interaction_score": 5,
        "happiness_score": 4.8,
        "depression_score": 3.8,
        "daily_gaming_hours": 11,
        "weekly_sessions": 25,
        "night_gaming_ratio": 0.91,
        "sleep_hours": 3.5,
        "toxic_exposure": 0.28,
        "microtransactions_spending": 105,
        "years_gaming": 7
    }
},
  {
    "riotId": "NightTiger#NA944",
    "rank": "Immortal",
    "agent": "Yoru",
    "hours": 2501,
    "winRate": "52%",
    "presetValues": {
        "stress_level": 1,
        "anxiety_score": 2.7,
        "aggression_score": 2.6,
        "loneliness_score": 5.3,
        "social_interaction_score": 0,
        "happiness_score": 1.4,
        "depression_score": 3,
        "daily_gaming_hours": 11,
        "weekly_sessions": 24,
        "night_gaming_ratio": 0.21,
        "sleep_hours": 12,
        "toxic_exposure": 0.61,
        "microtransactions_spending": 105,
        "years_gaming": 7
    }
},
  {
    "riotId": "ShadowRogue#SEA3275",
    "rank": "Silver",
    "agent": "Chamber",
    "hours": 2814,
    "winRate": "61%",
    "presetValues": {
        "stress_level": 1,
        "anxiety_score": 9.3,
        "aggression_score": 9,
        "loneliness_score": 2.8,
        "social_interaction_score": 4.4,
        "happiness_score": 5.5,
        "depression_score": 4.7,
        "daily_gaming_hours": 10,
        "weekly_sessions": 40,
        "night_gaming_ratio": 0.58,
        "sleep_hours": 4,
        "toxic_exposure": 0.36,
        "microtransactions_spending": 145,
        "years_gaming": 5
    }
},
  {
    "riotId": "AlphaQueen#SEA2519",
    "rank": "Platinum",
    "agent": "Gekko",
    "hours": 4971,
    "winRate": "40%",
    "presetValues": {
        "stress_level": 6,
        "anxiety_score": 1.2,
        "aggression_score": 6.6,
        "loneliness_score": 6.8,
        "social_interaction_score": 6.1,
        "happiness_score": 2.4,
        "depression_score": 8.7,
        "daily_gaming_hours": 6.5,
        "weekly_sessions": 10,
        "night_gaming_ratio": 0.18,
        "sleep_hours": 7.5,
        "toxic_exposure": 0.73,
        "microtransactions_spending": 150,
        "years_gaming": 15
    }
},
  {
    "riotId": "ToxicSpark#SEA20",
    "rank": "Silver",
    "agent": "Gekko",
    "hours": 4228,
    "winRate": "57%",
    "presetValues": {
        "stress_level": 2,
        "anxiety_score": 1.7,
        "aggression_score": 7.3,
        "loneliness_score": 9.1,
        "social_interaction_score": 1.6,
        "happiness_score": 8.3,
        "depression_score": 1.9,
        "daily_gaming_hours": 3,
        "weekly_sessions": 17,
        "night_gaming_ratio": 0.71,
        "sleep_hours": 4,
        "toxic_exposure": 0.88,
        "microtransactions_spending": 445,
        "years_gaming": 0
    }
},
  {
    "riotId": "BetaSniper#SEA2963",
    "rank": "Bronze",
    "agent": "Harbor",
    "hours": 3223,
    "winRate": "56%",
    "presetValues": {
        "stress_level": 10,
        "anxiety_score": 8.5,
        "aggression_score": 1.5,
        "loneliness_score": 0.3,
        "social_interaction_score": 0.8,
        "happiness_score": 5.2,
        "depression_score": 8.3,
        "daily_gaming_hours": 7.5,
        "weekly_sessions": 21,
        "night_gaming_ratio": 0.92,
        "sleep_hours": 10,
        "toxic_exposure": 0.92,
        "microtransactions_spending": 225,
        "years_gaming": 23
    }
},
  {
    "riotId": "ToxicGhost#EUNE8486",
    "rank": "Platinum",
    "agent": "Gekko",
    "hours": 4275,
    "winRate": "44%",
    "presetValues": {
        "stress_level": 10,
        "anxiety_score": 3.5,
        "aggression_score": 0.5,
        "loneliness_score": 9.7,
        "social_interaction_score": 9.2,
        "happiness_score": 2.2,
        "depression_score": 1.6,
        "daily_gaming_hours": 5,
        "weekly_sessions": 28,
        "night_gaming_ratio": 0.27,
        "sleep_hours": 4.5,
        "toxic_exposure": 0.24,
        "microtransactions_spending": 470,
        "years_gaming": 29
    }
},
  {
    "riotId": "StrikeDragon#LATAM2708",
    "rank": "Silver",
    "agent": "Chamber",
    "hours": 4317,
    "winRate": "61%",
    "presetValues": {
        "stress_level": 8,
        "anxiety_score": 1.3,
        "aggression_score": 6.7,
        "loneliness_score": 1.6,
        "social_interaction_score": 2.8,
        "happiness_score": 7.5,
        "depression_score": 7.6,
        "daily_gaming_hours": 4,
        "weekly_sessions": 25,
        "night_gaming_ratio": 0.21,
        "sleep_hours": 4.5,
        "toxic_exposure": 0.07,
        "microtransactions_spending": 295,
        "years_gaming": 7
    }
},
  {
    "riotId": "EliteReaper#KR8086",
    "rank": "Bronze",
    "agent": "Gekko",
    "hours": 148,
    "winRate": "63%",
    "presetValues": {
        "stress_level": 8,
        "anxiety_score": 2.9,
        "aggression_score": 7.8,
        "loneliness_score": 0,
        "social_interaction_score": 2.6,
        "happiness_score": 1.2,
        "depression_score": 1.4,
        "daily_gaming_hours": 15,
        "weekly_sessions": 9,
        "night_gaming_ratio": 0.76,
        "sleep_hours": 9.5,
        "toxic_exposure": 0.44,
        "microtransactions_spending": 100,
        "years_gaming": 24
    }
},
  {
    "riotId": "LightGod#JP4030",
    "rank": "Immortal",
    "agent": "Gekko",
    "hours": 1298,
    "winRate": "56%",
    "presetValues": {
        "stress_level": 7,
        "anxiety_score": 2.8,
        "aggression_score": 3.2,
        "loneliness_score": 4.7,
        "social_interaction_score": 1.1,
        "happiness_score": 9.2,
        "depression_score": 0.7,
        "daily_gaming_hours": 1.5,
        "weekly_sessions": 21,
        "night_gaming_ratio": 0.47,
        "sleep_hours": 9,
        "toxic_exposure": 0.23,
        "microtransactions_spending": 255,
        "years_gaming": 6
    }
},
  {
    "riotId": "DeadlyMage#EUW4101",
    "rank": "Silver",
    "agent": "Astra",
    "hours": 4456,
    "winRate": "52%",
    "presetValues": {
        "stress_level": 6,
        "anxiety_score": 4.6,
        "aggression_score": 3.1,
        "loneliness_score": 3.1,
        "social_interaction_score": 3.3,
        "happiness_score": 7.9,
        "depression_score": 5.4,
        "daily_gaming_hours": 15.5,
        "weekly_sessions": 41,
        "night_gaming_ratio": 0.75,
        "sleep_hours": 8,
        "toxic_exposure": 0.66,
        "microtransactions_spending": 165,
        "years_gaming": 19
    }
},
  {
    "riotId": "GhostRunner#JP2231",
    "rank": "Ascendant",
    "agent": "Astra",
    "hours": 2940,
    "winRate": "56%",
    "presetValues": {
        "stress_level": 6,
        "anxiety_score": 8,
        "aggression_score": 3.7,
        "loneliness_score": 7.4,
        "social_interaction_score": 7.6,
        "happiness_score": 0.4,
        "depression_score": 0,
        "daily_gaming_hours": 14,
        "weekly_sessions": 26,
        "night_gaming_ratio": 0.82,
        "sleep_hours": 12.5,
        "toxic_exposure": 0.5,
        "microtransactions_spending": 230,
        "years_gaming": 7
    }
},
  {
    "riotId": "HappyWolf#EUNE430",
    "rank": "Diamond",
    "agent": "Reyna",
    "hours": 4052,
    "winRate": "43%",
    "presetValues": {
        "stress_level": 7,
        "anxiety_score": 9.6,
        "aggression_score": 3,
        "loneliness_score": 0.7,
        "social_interaction_score": 1.7,
        "happiness_score": 1.6,
        "depression_score": 8.6,
        "daily_gaming_hours": 6.5,
        "weekly_sessions": 34,
        "night_gaming_ratio": 0.65,
        "sleep_hours": 5,
        "toxic_exposure": 0.16,
        "microtransactions_spending": 355,
        "years_gaming": 30
    }
},
  {
    "riotId": "CasualSniper#BR2962",
    "rank": "Silver",
    "agent": "Yoru",
    "hours": 648,
    "winRate": "46%",
    "presetValues": {
        "stress_level": 3,
        "anxiety_score": 4.2,
        "aggression_score": 6.8,
        "loneliness_score": 1.1,
        "social_interaction_score": 3.3,
        "happiness_score": 2.4,
        "depression_score": 1,
        "daily_gaming_hours": 2.5,
        "weekly_sessions": 19,
        "night_gaming_ratio": 0.69,
        "sleep_hours": 10,
        "toxic_exposure": 0.08,
        "microtransactions_spending": 220,
        "years_gaming": 28
    }
},
  {
    "riotId": "AlphaOracle#NA3022",
    "rank": "Iron",
    "agent": "Harbor",
    "hours": 3043,
    "winRate": "64%",
    "presetValues": {
        "stress_level": 4,
        "anxiety_score": 4.3,
        "aggression_score": 7.8,
        "loneliness_score": 2.8,
        "social_interaction_score": 8.8,
        "happiness_score": 7.7,
        "depression_score": 7,
        "daily_gaming_hours": 10.5,
        "weekly_sessions": 3,
        "night_gaming_ratio": 0.27,
        "sleep_hours": 12,
        "toxic_exposure": 0.5,
        "microtransactions_spending": 25,
        "years_gaming": 19
    }
},
  {
    "riotId": "CyberGhost#VLR2860",
    "rank": "Immortal",
    "agent": "Skye",
    "hours": 2787,
    "winRate": "61%",
    "presetValues": {
        "stress_level": 10,
        "anxiety_score": 3.5,
        "aggression_score": 8.5,
        "loneliness_score": 9.1,
        "social_interaction_score": 3.6,
        "happiness_score": 5.1,
        "depression_score": 1.1,
        "daily_gaming_hours": 10,
        "weekly_sessions": 36,
        "night_gaming_ratio": 0.06,
        "sleep_hours": 10.5,
        "toxic_exposure": 0.18,
        "microtransactions_spending": 40,
        "years_gaming": 5
    }
},
  {
    "riotId": "SwiftRunner#EUW9943",
    "rank": "Bronze",
    "agent": "Reyna",
    "hours": 4796,
    "winRate": "58%",
    "presetValues": {
        "stress_level": 10,
        "anxiety_score": 7.7,
        "aggression_score": 0.1,
        "loneliness_score": 8.5,
        "social_interaction_score": 2.4,
        "happiness_score": 4.6,
        "depression_score": 6.5,
        "daily_gaming_hours": 6,
        "weekly_sessions": 1,
        "night_gaming_ratio": 0.31,
        "sleep_hours": 12.5,
        "toxic_exposure": 0.18,
        "microtransactions_spending": 460,
        "years_gaming": 0
    }
},
  {
    "riotId": "LightRunner#SEA8774",
    "rank": "Immortal",
    "agent": "Yoru",
    "hours": 2125,
    "winRate": "44%",
    "presetValues": {
        "stress_level": 10,
        "anxiety_score": 0.9,
        "aggression_score": 3.3,
        "loneliness_score": 1.4,
        "social_interaction_score": 6,
        "happiness_score": 4.1,
        "depression_score": 6.6,
        "daily_gaming_hours": 0,
        "weekly_sessions": 9,
        "night_gaming_ratio": 0.08,
        "sleep_hours": 8,
        "toxic_exposure": 0.36,
        "microtransactions_spending": 140,
        "years_gaming": 30
    }
},
  {
    "riotId": "StrikeSpark#VLR1502",
    "rank": "Platinum",
    "agent": "Harbor",
    "hours": 2269,
    "winRate": "52%",
    "presetValues": {
        "stress_level": 5,
        "anxiety_score": 0.9,
        "aggression_score": 7,
        "loneliness_score": 5.3,
        "social_interaction_score": 6,
        "happiness_score": 2.7,
        "depression_score": 0.1,
        "daily_gaming_hours": 11.5,
        "weekly_sessions": 16,
        "night_gaming_ratio": 0.84,
        "sleep_hours": 10,
        "toxic_exposure": 0.58,
        "microtransactions_spending": 50,
        "years_gaming": 19
    }
},
  {
    "riotId": "EliteWalker#EUNE87",
    "rank": "Ascendant",
    "agent": "Viper",
    "hours": 2355,
    "winRate": "53%",
    "presetValues": {
        "stress_level": 7,
        "anxiety_score": 7.3,
        "aggression_score": 9.9,
        "loneliness_score": 7.7,
        "social_interaction_score": 6.6,
        "happiness_score": 4.8,
        "depression_score": 6.2,
        "daily_gaming_hours": 3,
        "weekly_sessions": 23,
        "night_gaming_ratio": 0.68,
        "sleep_hours": 12.5,
        "toxic_exposure": 0.3,
        "microtransactions_spending": 25,
        "years_gaming": 10
    }
},
  {
    "riotId": "VortexGod#SEA9939",
    "rank": "Platinum",
    "agent": "Breach",
    "hours": 3401,
    "winRate": "59%",
    "presetValues": {
        "stress_level": 6,
        "anxiety_score": 4.2,
        "aggression_score": 7.1,
        "loneliness_score": 8.9,
        "social_interaction_score": 0.2,
        "happiness_score": 7.9,
        "depression_score": 6.4,
        "daily_gaming_hours": 5.5,
        "weekly_sessions": 13,
        "night_gaming_ratio": 0.42,
        "sleep_hours": 13,
        "toxic_exposure": 0.5,
        "microtransactions_spending": 30,
        "years_gaming": 2
    }
},
  {
    "riotId": "HappySentinel#SEA2978",
    "rank": "Gold",
    "agent": "Deadlock",
    "hours": 3716,
    "winRate": "40%",
    "presetValues": {
        "stress_level": 1,
        "anxiety_score": 0.2,
        "aggression_score": 4.9,
        "loneliness_score": 1.6,
        "social_interaction_score": 5.9,
        "happiness_score": 4.4,
        "depression_score": 0.2,
        "daily_gaming_hours": 12,
        "weekly_sessions": 33,
        "night_gaming_ratio": 0.69,
        "sleep_hours": 10,
        "toxic_exposure": 0.28,
        "microtransactions_spending": 375,
        "years_gaming": 30
    }
}
];
